language: php
sudo: false

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

matrix:
  fast_finish: true

before_script:
  - phpenv config-add test/php.ini
  - composer install
  - php -i

script:
  - phpunit -c tests/units.sqlite.xml
